-- Disposable test transaction: automatic authority, restart recovery, restrictions and rankings.
begin;
insert into auth.users values('00000000-0000-0000-0000-000000000001'),('00000000-0000-0000-0000-000000000002');
insert into public.profiles(id,nickname) values('00000000-0000-0000-0000-000000000001','Member'),('00000000-0000-0000-0000-000000000002','Admin');
insert into public.user_roles values('00000000-0000-0000-0000-000000000002','admin');
insert into public.players(id,name,english,birth_date,provider,position) values('bsd-10','Lionel Messi','Lionel Messi','1987-06-24','bsd','FW');
create function pg_temp.expect_error(command text,expected text) returns void language plpgsql as $$begin
 begin execute command;exception when others then if sqlerrm=expected or sqlstate=expected then return;else raise;end if;end;
 raise exception 'Expected % from %',expected,command;
end $$;
set local role service_role;
do $$declare c jsonb;rev uuid;changed uuid;n int;begin
 c:=public.kickx_automation_claim();
 if not (c->>'daily')::boolean or c->>'day' is null then raise exception 'Daily claim missing';end if;
 if not (public.kickx_automation_claim()->>'busy')::boolean then raise exception 'Lease duplicated';end if;
 perform public.kickx_automatic_daily_start((c->>'token')::uuid,'[{"key":"test","kind":"league","priority":0,"payload":{"phase":"detail"},"label":"Test"}]');
 perform public.kickx_automatic_daily_finish_task((c->>'token')::uuid,'test','{"done":false,"payload":{"phase":"seasons"},"children":[]}');
 if (select payload->>'phase' from public.automation_daily_tasks where key='test')<>'seasons' then raise exception 'Checkpoint not persisted';end if;
 perform public.kickx_automation_finish((c->>'token')::uuid,false,'{}','NETWORK_RETRY');
 c:=public.kickx_automation_claim();
 perform public.kickx_automatic_daily_start((c->>'token')::uuid,'[{"key":"test","kind":"league","priority":0,"payload":{"phase":"detail"},"label":"Test"}]');
 if (select payload->>'phase' from public.automation_daily_tasks where key='test')<>'seasons' then raise exception 'Resume reset checkpoint';end if;
 perform public.kickx_automatic_daily_finish_task((c->>'token')::uuid,'test','{"done":true,"children":[]}');
 perform public.kickx_automation_finish((c->>'token')::uuid,true,'{}');
 c:=public.kickx_automation_claim();if (c->>'daily')::boolean then raise exception 'Daily success ignored';end if;
 perform public.kickx_automation_finish((c->>'token')::uuid,false,'{}');
 select revision into rev from public.calculation_queue where player_id='bsd-10';
 perform public.kickx_queue_player('bsd-10');select revision into changed from public.calculation_queue where player_id='bsd-10';
 if rev=changed then raise exception 'Queue revision not advanced';end if;
 perform public.kickx_ack_calculation('bsd-10',rev);
 if not exists(select 1 from public.calculation_queue where revision=changed) then raise exception 'Stale ACK erased work';end if;
 perform public.kickx_ack_calculation('bsd-10',changed,'CALCULATION_WITHHELD');
 if not exists(select 1 from public.calculation_queue where attempts=1 and retry_at>now()) then raise exception 'Retry absent';end if;
 n:=public.kickx_auto_initialize_market();if n<>1 then raise exception 'Base not initialized';end if;
 if public.kickx_auto_initialize_market()<>0 then raise exception 'Base initialized twice';end if;
 if not public.kickx_apply_automatic_name('bsd-10','리오넬 메시',array['Lionel Messi'],'Q123','{"name":"Lionel Messi","english":"Lionel Messi","birth_date":"1987-06-24"}') then raise exception 'Name not saved';end if;
end $$;
reset role;
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000001';
select pg_temp.expect_error('select public.kickx_automation_claim()','42501');
select pg_temp.expect_error('select public.kickx_auto_initialize_market()','42501');
select pg_temp.expect_error('select * from public.calculation_queue','42501');
select pg_temp.expect_error($q$select public.kickx_restrict_member('00000000-0000-0000-0000-000000000002',7,'test reason')$q$,'ADMIN_REQUIRED');
select public.kickx_open_wallet();
reset role;
do $$declare rows jsonb;q jsonb;begin
 select s.rows into rows from public.ranking_snapshots s where period='weekly' order by calculated_at desc limit 1;
 if jsonb_array_length(rows)<>1 then raise exception 'Wallet did not refresh ranking';end if;
end $$;
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000002';
select pg_temp.expect_error($q$select public.kickx_restrict_member('00000000-0000-0000-0000-000000000002',7,'test reason')$q$,'PROTECTED_ADMIN');
select public.kickx_restrict_member('00000000-0000-0000-0000-000000000001',7,'Repeated spam');
select public.kickx_save_player_name('bsd-10','手動한글',array['Manual']);
reset role;
set local role service_role;
do $$begin
 if public.kickx_apply_automatic_name('bsd-10','리오넬 메시',array['Lionel Messi'],'Q123','{"name":"Lionel Messi","english":"Lionel Messi","birth_date":"1987-06-24"}') then raise exception 'Manual name overwritten';end if;
end $$;
reset role;
set local role authenticated;
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000001';
select pg_temp.expect_error($q$select public.kickx_quote('bsd-10','buy')$q$,'MEMBER_SUSPENDED');
select pg_temp.expect_error($q$select public.kickx_save_squad('4-3-3',array_fill(null::text,array[11]),0)$q$,'MEMBER_SUSPENDED');
select pg_temp.expect_error($q$select public.kickx_community_write('like','{}')$q$,'MEMBER_SUSPENDED');
select pg_temp.expect_error($q$update public.profiles set nickname='Bypass' where id='00000000-0000-0000-0000-000000000001'$q$,'MEMBER_SUSPENDED');
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000002';
select public.kickx_restrict_member('00000000-0000-0000-0000-000000000001',0,'Appeal accepted');
set local request.jwt.claim.sub='00000000-0000-0000-0000-000000000001';
select public.kickx_quote('bsd-10','buy');
reset role;
rollback;
