export type Position = "GK" | "DF" | "MF" | "FW";
export type Player = {
  id: string;
  name: string;
  english: string;
  short: string;
  team: string;
  position: Position;
  number: number;
  country: string;
  age: number;
  price: number;
  change: number;
  performance: number;
  volume: number;
  goals: number;
  assists: number;
  minutes: number;
  history: number[];
  status?: string;
};
export const teams = [
  {
    id: "arsenal",
    name: "아스널",
    english: "Arsenal",
    code: "ARS",
    color: "#e25563",
    league: "프리미어리그",
  },
  {
    id: "man-city",
    name: "맨체스터 시티",
    english: "Manchester City",
    code: "MCI",
    color: "#8bc7ef",
    league: "프리미어리그",
  },
  {
    id: "liverpool",
    name: "리버풀",
    english: "Liverpool",
    code: "LIV",
    color: "#ef6470",
    league: "프리미어리그",
  },
  {
    id: "real-madrid",
    name: "레알 마드리드",
    english: "Real Madrid",
    code: "RMA",
    color: "#d8d9eb",
    league: "라리가",
  },
  {
    id: "barcelona",
    name: "바르셀로나",
    english: "Barcelona",
    code: "BAR",
    color: "#c084cf",
    league: "라리가",
  },
  {
    id: "bayern",
    name: "바이에른 뮌헨",
    english: "Bayern München",
    code: "BAY",
    color: "#f67782",
    league: "분데스리가",
  },
  {
    id: "leverkusen",
    name: "레버쿠젠",
    english: "Leverkusen",
    code: "B04",
    color: "#df6372",
    league: "분데스리가",
  },
  {
    id: "inter",
    name: "인터 밀란",
    english: "Inter Milan",
    code: "INT",
    color: "#799bff",
    league: "세리에 A",
  },
  {
    id: "psg",
    name: "파리 생제르맹",
    english: "Paris Saint-Germain",
    code: "PSG",
    color: "#74a1df",
    league: "리그 1",
  },
];
export const leagues = [
  "프리미어리그",
  "라리가",
  "분데스리가",
  "세리에 A",
  "리그 1",
];
const rows: Omit<Player, "history">[] = [
  {
    id: "haaland",
    name: "엘링 홀란",
    english: "Erling Haaland",
    short: "Haaland",
    team: "man-city",
    position: "FW",
    number: 9,
    country: "노르웨이",
    age: 26,
    price: 15200,
    change: 4.2,
    performance: 92,
    volume: 1842,
    goals: 8,
    assists: 1,
    minutes: 540,
  },
  {
    id: "saka",
    name: "부카요 사카",
    english: "Bukayo Saka",
    short: "Saka",
    team: "arsenal",
    position: "FW",
    number: 7,
    country: "잉글랜드",
    age: 25,
    price: 12100,
    change: 2.8,
    performance: 87,
    volume: 1284,
    goals: 4,
    assists: 5,
    minutes: 518,
  },
  {
    id: "bellingham",
    name: "주드 벨링엄",
    english: "Jude Bellingham",
    short: "Bellingham",
    team: "real-madrid",
    position: "MF",
    number: 5,
    country: "잉글랜드",
    age: 23,
    price: 13850,
    change: 3.1,
    performance: 89,
    volume: 1526,
    goals: 5,
    assists: 3,
    minutes: 526,
  },
  {
    id: "rodri",
    name: "로드리",
    english: "Rodri",
    short: "Rodri",
    team: "man-city",
    position: "MF",
    number: 16,
    country: "스페인",
    age: 30,
    price: 11760,
    change: -1.8,
    performance: 81,
    volume: 642,
    goals: 1,
    assists: 2,
    minutes: 482,
  },
  {
    id: "kane",
    name: "해리 케인",
    english: "Harry Kane",
    short: "Kane",
    team: "bayern",
    position: "FW",
    number: 9,
    country: "잉글랜드",
    age: 33,
    price: 14400,
    change: -1.2,
    performance: 85,
    volume: 973,
    goals: 7,
    assists: 2,
    minutes: 538,
  },
  {
    id: "saliba",
    name: "윌리엄 살리바",
    english: "William Saliba",
    short: "Saliba",
    team: "arsenal",
    position: "DF",
    number: 2,
    country: "프랑스",
    age: 25,
    price: 7200,
    change: 2.4,
    performance: 84,
    volume: 725,
    goals: 0,
    assists: 1,
    minutes: 540,
  },
  {
    id: "dias",
    name: "후벵 디아스",
    english: "Ruben Dias",
    short: "Dias",
    team: "man-city",
    position: "DF",
    number: 3,
    country: "포르투갈",
    age: 29,
    price: 6600,
    change: 1.6,
    performance: 82,
    volume: 526,
    goals: 0,
    assists: 0,
    minutes: 540,
  },
  {
    id: "alisson",
    name: "알리송 베케르",
    english: "Alisson Becker",
    short: "Alisson",
    team: "liverpool",
    position: "GK",
    number: 1,
    country: "브라질",
    age: 33,
    price: 5900,
    change: 0.8,
    performance: 80,
    volume: 418,
    goals: 0,
    assists: 0,
    minutes: 540,
  },
  {
    id: "rice",
    name: "데클런 라이스",
    english: "Declan Rice",
    short: "Rice",
    team: "arsenal",
    position: "MF",
    number: 41,
    country: "잉글랜드",
    age: 27,
    price: 6800,
    change: 1.9,
    performance: 83,
    volume: 784,
    goals: 1,
    assists: 3,
    minutes: 535,
  },
  {
    id: "gabriel",
    name: "가브리에우 마갈량이스",
    english: "Gabriel Magalhaes",
    short: "Gabriel",
    team: "arsenal",
    position: "DF",
    number: 6,
    country: "브라질",
    age: 28,
    price: 6200,
    change: 1.3,
    performance: 79,
    volume: 429,
    goals: 1,
    assists: 0,
    minutes: 540,
  },
  {
    id: "hakimi",
    name: "아슈라프 하키미",
    english: "Achraf Hakimi",
    short: "Hakimi",
    team: "psg",
    position: "DF",
    number: 2,
    country: "모로코",
    age: 27,
    price: 5800,
    change: 2.2,
    performance: 85,
    volume: 568,
    goals: 2,
    assists: 3,
    minutes: 507,
  },
  {
    id: "yamal",
    name: "라민 야말",
    english: "Lamine Yamal",
    short: "Yamal",
    team: "barcelona",
    position: "FW",
    number: 10,
    country: "스페인",
    age: 19,
    price: 13900,
    change: 5.6,
    performance: 94,
    volume: 2156,
    goals: 4,
    assists: 6,
    minutes: 492,
  },
  {
    id: "lautaro",
    name: "라우타로 마르티네스",
    english: "Lautaro Martinez",
    short: "Lautaro",
    team: "inter",
    position: "FW",
    number: 10,
    country: "아르헨티나",
    age: 29,
    price: 11200,
    change: 2.7,
    performance: 88,
    volume: 861,
    goals: 6,
    assists: 2,
    minutes: 521,
  },
  {
    id: "wirtz",
    name: "플로리안 비르츠",
    english: "Florian Wirtz",
    short: "Wirtz",
    team: "liverpool",
    position: "MF",
    number: 7,
    country: "독일",
    age: 23,
    price: 10800,
    change: 3.6,
    performance: 90,
    volume: 1386,
    goals: 3,
    assists: 5,
    minutes: 494,
  },
  {
    id: "valverde",
    name: "페데리코 발베르데",
    english: "Federico Valverde",
    short: "Valverde",
    team: "real-madrid",
    position: "MF",
    number: 8,
    country: "우루과이",
    age: 28,
    price: 9200,
    change: -0.7,
    performance: 82,
    volume: 613,
    goals: 2,
    assists: 2,
    minutes: 540,
  },
  {
    id: "raya",
    name: "다비드 라야",
    english: "David Raya",
    short: "Raya",
    team: "arsenal",
    position: "GK",
    number: 1,
    country: "스페인",
    age: 31,
    price: 5400,
    change: 1.4,
    performance: 84,
    volume: 362,
    goals: 0,
    assists: 0,
    minutes: 540,
  },
  {
    id: "musiala",
    name: "자말 무시알라",
    english: "Jamal Musiala",
    short: "Musiala",
    team: "bayern",
    position: "MF",
    number: 10,
    country: "독일",
    age: 23,
    price: 10600,
    change: -2.4,
    performance: 77,
    volume: 586,
    goals: 2,
    assists: 2,
    minutes: 360,
    status: "거래 중지",
  },
  {
    id: "dembele",
    name: "우스만 뎀벨레",
    english: "Ousmane Dembele",
    short: "Dembélé",
    team: "psg",
    position: "FW",
    number: 10,
    country: "프랑스",
    age: 29,
    price: 11800,
    change: 4.8,
    performance: 91,
    volume: 1648,
    goals: 6,
    assists: 4,
    minutes: 481,
  },
];
export const players: Player[] = rows.map((p, i) => ({
  ...p,
  history: Array.from({ length: 30 }, (_, n) =>
    Math.round(
      p.price * (0.84 + (n * 0.16) / 29 + Math.sin(n * 1.8 + i) * 0.017),
    ),
  ).map((v, n) => (n === 29 ? p.price : v)),
}));
export const getPlayer = (id: string) => players.find((p) => p.id === id);
export const getTeam = (id: string) => teams.find((t) => t.id === id)!;
export const money = (n: number) =>
  new Intl.NumberFormat("ko-KR").format(Math.round(n));
export const percent = (n: number) => `${n >= 0 ? "+" : ""}${n.toFixed(1)}%`;
export const fixtures = [
  {
    id: 1,
    league: "프리미어리그",
    home: "arsenal",
    away: "man-city",
    date: "09.27",
    day: "일",
    time: "20:30",
  },
  {
    id: 2,
    league: "라리가",
    home: "barcelona",
    away: "real-madrid",
    date: "09.28",
    day: "월",
    time: "04:00",
  },
  {
    id: 3,
    league: "분데스리가",
    home: "bayern",
    away: "leverkusen",
    date: "09.28",
    day: "월",
    time: "22:30",
  },
];
export type Transaction = {
  id: string;
  playerId: string;
  type: "buy" | "sell";
  price: number;
  fee: number;
  net: number;
  date: string;
};
export type Post = {
  id: string;
  author: string;
  authorId: string;
  scope: "club" | "player";
  target: string;
  category: string;
  title: string;
  body: string;
  date: string;
  likes: number;
  views: number;
  transaction?: Transaction;
  hidden?: boolean;
};
export type Comment = {
  id: string;
  postId: string;
  author: string;
  authorId: string;
  body: string;
  date: string;
  hidden?: boolean;
};
export const initialPosts: Post[] = [
  {
    id: "post-1",
    author: "NorthLondon",
    authorId: "north",
    scope: "club",
    target: "arsenal",
    category: "경기 이야기",
    title: "이번 맨시티전, 중원 싸움이 정말 기대되네요",
    body: "라이스가 보여 주는 중원 장악력이 좋아서 이번 맞대결이 기다려집니다.\n\n점유율보다 전환 순간에 얼마나 빠르게 연결하느냐가 관건일 것 같아요. 여러분은 어떤 선수를 가장 주목하고 계신가요?",
    date: "2026-09-25T10:30:00.000Z",
    likes: 24,
    views: 328,
  },
  {
    id: "post-2",
    author: "블루문",
    authorId: "blue",
    scope: "player",
    target: "haaland",
    category: "선수 분석",
    title: "홀란의 득점력, 지금 가격에도 매력적일까요?",
    body: "예시 경기 기록을 보면 최근 득점 흐름이 좋아 보입니다.\n\n이미 많이 오른 가격인 만큼 앞으로의 경기 일정도 함께 보려고 합니다. 한 경기의 Performance와 시장 가격은 별개라는 점도 생각해야겠죠.",
    date: "2026-09-25T09:20:00.000Z",
    likes: 18,
    views: 246,
  },
  {
    id: "post-3",
    author: "KICKER",
    authorId: "me",
    scope: "player",
    target: "saka",
    category: "거래 이야기",
    title: "사카 영입 완료! 이제 차분히 지켜보려고요",
    body: "골과 도움을 모두 기대할 수 있는 선수를 찾다가 사카를 선택했습니다.\n\n이번 영입으로 공격진 구성을 마쳤어요. 다음 경기가 더 재미있어질 것 같습니다.",
    date: "2026-09-25T08:10:00.000Z",
    likes: 12,
    views: 184,
    transaction: {
      id: "seed-saka",
      playerId: "saka",
      type: "buy",
      price: 11000,
      fee: 0,
      net: 11000,
      date: "2026-09-20T08:00:00.000Z",
    },
  },
  {
    id: "post-4",
    author: "Bernabéu",
    authorId: "real",
    scope: "club",
    target: "real-madrid",
    category: "자유 이야기",
    title: "엘 클라시코 앞두고 다들 준비되셨나요?",
    body: "이번 경기는 중원 조합이 가장 궁금하네요. 응원하면서 선수 기록도 같이 살펴볼 예정입니다.",
    date: "2026-09-25T07:20:00.000Z",
    likes: 31,
    views: 405,
  },
  {
    id: "post-5",
    author: "Gunner04",
    authorId: "gunner",
    scope: "club",
    target: "arsenal",
    category: "선수 분석",
    title: "살리바와 가브리에우, 수비진의 안정감",
    body: "화려한 공격수도 좋지만 수비진의 꾸준함에 주목하고 있어요. 클린시트와 출전시간을 같이 보는 편입니다.",
    date: "2026-09-24T14:10:00.000Z",
    likes: 16,
    views: 211,
  },
  {
    id: "post-6",
    author: "라리가노트",
    authorId: "liga",
    scope: "player",
    target: "yamal",
    category: "선수 분석",
    title: "야말의 최근 경기 흐름을 정리해 봤습니다",
    body: "예시 데이터에서는 기회 창출과 득점 모두 좋은 흐름입니다. 가격의 움직임과 경기력을 구분해서 살펴보세요.",
    date: "2026-09-24T11:45:00.000Z",
    likes: 22,
    views: 296,
  },
];
export const formations: Record<string, Position[]> = {
  "4-3-3": ["FW", "FW", "FW", "MF", "MF", "MF", "DF", "DF", "DF", "DF", "GK"],
  "4-4-2": ["FW", "FW", "MF", "MF", "MF", "MF", "DF", "DF", "DF", "DF", "GK"],
  "3-5-2": ["FW", "FW", "MF", "MF", "MF", "MF", "MF", "DF", "DF", "DF", "GK"],
};
export const initialSquad = [
  "saka",
  "haaland",
  "lautaro",
  "bellingham",
  "rice",
  "rodri",
  "gabriel",
  "saliba",
  "dias",
  "hakimi",
  "alisson",
];
export const seedHoldings = initialSquad.map((id, i) => ({
  playerId: id,
  cost: Math.round(getPlayer(id)!.price * (0.86 + (i % 4) * 0.025)),
  date: "2026-09-20T08:00:00.000Z",
}));
export const seedTransactions: Transaction[] = seedHoldings.map((h, i) => ({
  id: `seed-${h.playerId}`,
  playerId: h.playerId,
  type: "buy",
  price: h.cost,
  fee: 0,
  net: h.cost,
  date: `2026-09-${String(24 - Math.floor(i / 3)).padStart(2, "0")}T${String(14 - (i % 3)).padStart(2, "0")}:30:00.000Z`,
}));
export const jobsSeed = [
  {
    id: "SYNC-0925-03",
    name: "선수 경기 기록 수집",
    kind: "수집",
    target: "프리미어리그 · 경기 6건",
    time: "09.25 19:45",
    status: "실패",
    success: 121,
    fail: 3,
    error: "선수 3명의 출전시간 누락. 원본 응답 확인 필요.",
  },
  {
    id: "PERF-0925-02",
    name: "Performance 계산",
    kind: "계산",
    target: "확정 선수 기록 121건",
    time: "09.25 19:42",
    status: "완료",
    success: 121,
    fail: 0,
    error: "",
  },
  {
    id: "PRICE-0925-02",
    name: "선수 가치 갱신",
    kind: "가격",
    target: "선수 121명 · 시연 규칙 v0.1",
    time: "09.25 19:43",
    status: "완료",
    success: 121,
    fail: 0,
    error: "",
  },
  {
    id: "SYNC-0925-01",
    name: "리그 / 구단 정보 수집",
    kind: "수집",
    target: "유럽 5대 리그",
    time: "09.25 18:00",
    status: "완료",
    success: 96,
    fail: 0,
    error: "",
  },
];
export const rankings = [
  {
    id: "r1",
    name: "터치라인",
    team: "liverpool",
    asset: 168420,
    weekly: 24.8,
    monthly: 38.2,
  },
  {
    id: "r2",
    name: "BlueMoon",
    team: "man-city",
    asset: 156810,
    weekly: 22.4,
    monthly: 32.6,
  },
  {
    id: "r3",
    name: "NorthLondon",
    team: "arsenal",
    asset: 149200,
    weekly: 19.6,
    monthly: 30.1,
  },
  {
    id: "r4",
    name: "마드리디스타",
    team: "real-madrid",
    asset: 143670,
    weekly: 17.5,
    monthly: 24.3,
  },
  {
    id: "r5",
    name: "축구보는개발자",
    team: "barcelona",
    asset: 139280,
    weekly: 15.8,
    monthly: 21.2,
  },
  {
    id: "r6",
    name: "MiaSanMia",
    team: "bayern",
    asset: 138540,
    weekly: 13.2,
    monthly: 19.8,
  },
  {
    id: "r7",
    name: "LaDecima",
    team: "real-madrid",
    asset: 134290,
    weekly: 11.7,
    monthly: 16.5,
  },
];
